upgrade openpyxl=2.5.7, instead of un-specified
Previously, got
```
ImportError: Pandas requires version '2.5.7' or newer of 'openpyxl' (version '2.4.0-b1' currently installed).
```